# Define docker-compose version
version: '3.5'

# Define services
services:
    mariadb:
        container_name: mariadb
        image: mariadb
        build:
            context: ./requirements/mariadb
        environment:
            - MYSQL_DATABASE=wpdb
            - MYSQL_USER=wpuser
            - MYSQL_PASSWORD=dbpassword
            - MYSQL_ROOT_PASSWORD=dbpassword
        networks:
            - docker-network
        volumes:
            - db:/var/lib/mysql
        restart: always

    wordpress:
        container_name: wordpress
        image: wordpress
        build:
            context: ./requirements/wordpress
        networks:
            - docker-network
        depends_on:
            - mariadb
        restart: always
        volumes:
            - wordpress:/var/www/html/wordpress
            - phpmyadmin:/var/www/html/phpmyadmin

    nginx:
        container_name: nginx
        image: nginx
        build:
            context: ./requirements/nginx
        ports:
            - "443:443"
        networks:
            - docker-network
        volumes:
            - wordpress:/var/www/html/wordpress
            - phpmyadmin:/var/www/html/phpmyadmin
        depends_on:
            - wordpress
        restart: always

# Define network
networks:
    docker-network:

# Define volumes
volumes:
    wordpress:
    db:
    phpmyadmin:
