# Define docker-compose version
version: '3.5'

# Define services
services:
    mariadb:
        container_name: mariadb
        image: mariadb
        build:
            context: ./requirements/mariadb
        environment:
            - MYSQL_DATABASE=$MYSQL_DATABASE
            - MYSQL_USER=$MYSQL_USER
            - MYSQL_PASSWORD=$MYSQL_PASSWORD
            - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
        networks:
            - docker-network
        volumes:
            - db:/var/lib/mysql
        restart: always

    wordpress:
        container_name: wordpress
        image: wordpress
        build:
            context: ./requirements/wordpress
        environment:
            - MYSQL_DATABASE=$MYSQL_DATABASE
            - MYSQL_USER=$MYSQL_USER
            - MYSQL_PASSWORD=$MYSQL_PASSWORD
            - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
        networks:
            - docker-network
        depends_on:
            - mariadb
        restart: always
        volumes:
            - wordpress_files:/var/www/html/wordpress
            - phpmyadmin_files:/var/www/html/phpmyadmin
            - wordpress_files:/var/www/$DOMAIN_NAME/wordpress
            - phpmyadmin_files:/var/www/$DOMAIN_NAME/phpmyadmin

    nginx:
        container_name: nginx
        image: nginx
        build:
            context: ./requirements/nginx
        ports:
            - "443:443"
        networks:
            - docker-network
        volumes:
            - wordpress_files:/var/www/html/wordpress
            - phpmyadmin_files:/var/www/html/phpmyadmin
            - wordpress_files:/var/www/$DOMAIN_NAME/wordpress
            - phpmyadmin_files:/var/www/$DOMAIN_NAME/phpmyadmin
        depends_on:
            - wordpress
        restart: always

# Define network
networks:
    docker-network:

# Define volumes
volumes:
    wordpress_files:
        name: wordpress_files
        driver_opts:
            type: none
            device: /home/tnishina/data/wordpress_files
            o: bind
    db:
        name: db
        driver_opts:
            type: none
            device: /home/tnishina/data/db
            o: bind
    phpmyadmin_files:
        name: phpmyadmin_files
